image: debian/testing
packages:
    - curl
    - golang
    - zip
    - unzip
    - default-jdk-headless
    - pkg-config
    - libwayland-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxkbcommon-x11-dev
    - libxcursor-dev
    - libgles2-mesa-dev
    - libegl1-mesa-dev
    - libffi-dev
secrets:
    - c36d8148-24ea-4c82-843d-6223649368bb
    - 536ae4e3-5a52-4d4f-a48c-daa63ed9819a
    - dfa34fc4-a789-4cbd-bfcf-edfe02a7eec0
sources:
    - https://git.sr.ht/~whereswaldon/sprig
environment:
    PATH: /usr/bin:/home/build/go/bin:/home/build/android/cmdline-tools/tools/bin
    ANDROID_HOME: /home/build/android
    ANDROID_SDK_ROOT: /home/build/android
    android_sdk_tools_zip: commandlinetools-linux-6200805_latest.zip
    android_ndk_zip: android-ndk-r20-linux-x86_64.zip
    android_target_platform: "platforms;android-28"
    android_target_build_tools: "build-tools;28.0.2"
    GO111MODULE: "on"
    github_mirror: git@github.com:arborchat/sprig
triggers:
 - action: email
   condition: always
   to: ~whereswaldon/arbor-ci@lists.sr.ht
tasks:
 - test: |
    cd sprig
    go test -v -cover ./...
 - mirror: |
    # mirror to github while we wait for android
    ssh-keyscan github.com > "$HOME"/.ssh/known_hosts && cd sprig && git push --mirror "$github_mirror" || echo "failed mirroring"
 - install_mage: go get github.com/magefile/mage
 - build_windows: |
    cd sprig
    make windows
 - build_linux: |
    cd sprig
    make linux
 - install_android: |
    cd sprig
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    cd ..
    mkdir -p android/cmdline-tools
    cd android/cmdline-tools
    curl -so sdk-tools.zip "https://dl.google.com/android/repository/$android_sdk_tools_zip"
    unzip -q sdk-tools.zip
    rm sdk-tools.zip
    cd ..
    curl -so ndk.zip "https://dl.google.com/android/repository/$android_ndk_zip"
    unzip -q ndk.zip
    rm ndk.zip
    mv android-ndk-* ndk-bundle
    yes | sdkmanager --licenses
    sdkmanager "$android_target_platform" "$android_target_build_tools"
 - build_apk: |
    cd sprig
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    mv appicon-release.png appicon.png
    make APPID=chat.arbor.sprig sprig.apk
 - release: |
    cd sprig
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    tag=$(git describe --exact-match HEAD)
    source ~/.srht_token
    set -x
    for artifact in sprig.apk sprig-windows.zip sprig-linux.tar.xz ; do
        artifact_versioned=$(echo "$artifact" | sed -E "s|sprig|sprig-$tag|")
        mv -v "$artifact" "$artifact_versioned"
        artifact="$artifact_versioned"
        set +x
        echo curl -H "Authorization: token <token>" -F "file=@$artifact" "https://git.sr.ht/api/repos/sprig/artifacts/$tag"
        curl -H "Authorization: token $SRHT_TOKEN" -F "file=@$artifact" "https://git.sr.ht/api/repos/sprig/artifacts/$tag"
        set -x
    done
